services:
  postgresdb:
    extends:
      file: ./server/docker-compose.yml
      service: postgresdb
    networks:
      - ceja_network

  ceja:
    container_name: ceja-server
    build:
      context: ./server
      dockerfile: dockerfile.prod
    env_file: ./server/.env
    ports:
      - 3000:3000
    depends_on:
      - postgresdb
    networks:
      - ceja_network
  frontend:
    build:
      context: ./web
    ports:
      - 80:80
    env_file: ./web/.env
    depends_on:
      - ceja
    networks:
      - ceja_network

networks:
  ceja_network:
    driver: bridge

volumes:
  ceja_volume:
    driver: local
