FROM node:20

WORKDIR /app

COPY package.json package-lock.json ./

RUN ["npm", "ci"]

COPY . .

COPY api-entrypoint.sh /usr/local/bin/init.sh

RUN chmod +x /usr/local/bin/init.sh

ENTRYPOINT ["/usr/local/bin/init.sh"]

EXPOSE 3000

CMD ["npm", "run", "dev"]