FROM node:20 as build

WORKDIR /app
COPY package.json package-lock.json ./
RUN ["npm", "ci"]

COPY . .
RUN ["npm", "run", "build"]


FROM node:20-alpine

WORKDIR /app
COPY --from=build app/package.json app/package-lock.json ./
RUN npm ci --production

COPY ./server/api-entrypoint.sh /usr/local/bin/init.sh
RUN chmod +x /usr/local/bin/init.sh
ENTRYPOINT ["/usr/local/bin/init.sh"]

COPY --from=build app/prisma .
COPY --from=build app/dist ./dist


CMD ["npm", "run", "start"]